# Rellenar tabla de categorias #
INSERT INTO categorias VALUES (null, 'Accion');
INSERT INTO categorias VALUES (null, 'Aventura');
INSERT INTO categorias VALUES (null, 'Deprtes');


# RELLENAR TABLA DE ENTRADAS #
INSERT INTO entradas VALUES (null, 1, 1, 'DRAGON BALL Z', 'DESCRIPCION DEL JUEGO', CURDATE());
INSERT INTO entradas VALUES (null, 1, 2, 'GTA 5', 'DESCRIPCION DEL JUEGO', CURDATE());
INSERT INTO entradas VALUES (null, 1, 3, 'EFOOTBALL', 'DESCRIPCION DEL JUEGO', CURDATE());

INSERT INTO entradas VALUES (null, 2, 1, 'TEKKEN', 'DESCRIPCION DEL JUEGO', CURDATE());
INSERT INTO entradas VALUES (null, 2, 2, 'LEGO', 'DESCRIPCION DEL JUEGO', CURDATE());
INSERT INTO entradas VALUES (null, 2, 3, 'FIFA', 'DESCRIPCION DEL JUEGO', CURDATE());

INSERT INTO entradas VALUES (null, 3, 1, 'GUERRA', 'DESCRIPCION DEL JUEGO', CURDATE());
INSERT INTO entradas VALUES (null, 3, 2, 'AVENTURA', 'DESCRIPCION DEL JUEGO', CURDATE());
INSERT INTO entradas VALUES (null, 3, 3, 'CARRERAS', 'DESCRIPCION DEL JUEGO', CURDATE());


